### ISSUE TITLE
TypeError when running the benchmark

### ISSUE THREAD

**Issue by jmairal** [benchopt/benchmark_ols#4]
Here is an output of  benchopt run benchmark_ols

Boston                                                                                              
|--Ordinary Least Squares[fit_intercept=False]                                                      
|----cd: not installed                                                        
Traceback (most recent call last):
  File "/opt/miniconda3/bin/benchopt", line 33, in <module>
    sys.exit(load_entry_point('benchopt', 'console_scripts', 'benchopt')())
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/miniconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/cli.py", line 108, in run
    timeout=timeout, plot_result=not no_plot, pdb=pdb
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/runner.py", line 384, in run_benchmark
    force=force, pdb=pdb
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/runner.py", line 216, in run_one_solver
    solver._set_objective(objective)
  File "/mnt/lindonnees/willow/code/benchs/benchopt/benchopt/base.py", line 54, in _set_objective
    self.set_objective(**objective.to_dict())
TypeError: set_objective() got an unexpected keyword argument 'fit_intercept'

**Comment by agramfort** [comment]
are you using latest benchopt master version?

>

**Comment by jmairal** [comment]
I was not, but after updating benchopt, the issue remains.

**Comment by agramfort** [comment]
it works fine with me and I see fit_intercept in objective

https://github.com/benchopt/benchmark_ols/blob/master/objective.py#L11

is your benchmark folder up to date too?

>

**Comment by jmairal** [comment]
I cannot see what is wrong right now. It seems to me that both are updated :   benchmark_ols/objective.py contains  ```def __init__(self, fit_intercept=False):'''   

I will try again in the next few days in a clean environment

**Comment by jmairal** [comment]
That was my fault. I will not tell you what it was because it was too stupid.
